### ISSUE TITLE
[question] Flash size

### ISSUE THREAD

**Issue by higaski** [radimkarnis/esp32s2-wasm-demo#1]
Hello

Very interesting demo you have put up there. I wondered if you can maybe say some things about the binary size of the firmware and wasm snippet?

**Comment by radimkarnis** [comment]
Hello @higaski.
thanks for your interest!

This repo is generated from [this template](https://github.com/igrr/esp32s2-wasm-demo) by @igrr. I recommend asking Ivan for more information 😊
